Repository sveltejs/sapper, pull requests merged in 2020-09, with the labels that each got.

#1489 Fix CSS issue due to circular dependency in Sapper
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/create_compilers/RollupCompiler.ts
  test/apps/css/src/routes/index2.svelte
  test/apps/css/test.ts
Labels: bug

#1494 Handle dynamic css imports that are also statically imported
  package-lock.json
  package.json
  src/core/create_compilers/RollupCompiler.ts
  test/apps/css/rollup.config.js
  test/apps/css/src/routes/title.svelte
Labels: bug, bundling

#1508 Inject CSS loading with Rollup
  package-lock.json
  package.json
  runtime/src/app/app.ts
  runtime/src/internal/manifest-client.d.ts
  src/api/build.ts
  src/api/dev.ts
  src/core/create_app.ts
  src/core/create_compilers/RollupCompiler.ts
  src/core/create_compilers/code.ts
  src/core/create_compilers/inject.ts
Labels: bundling

#1515 Don't use facadeModuleId during css code splitting
  src/core/create_compilers/RollupCompiler.ts
Labels: bundling

#1524 Minify and hash inject_styles.js
  src/core/create_compilers/RollupCompiler.ts
Labels: bundling

#1434 Routing refactor
  runtime/src/app/app.ts
  runtime/src/app/goto/index.ts
  runtime/src/app/index.ts
  runtime/src/app/prefetch/index.ts
  runtime/src/app/router/index.ts
  runtime/src/app/start/index.ts
Labels: routing

#1525 IE 11 support
  package-lock.json
  package.json
  src/core/create_compilers/RollupCompiler.ts
Labels: bundling

#1498 Store `error` in page store (when an error page is triggered)
  runtime/src/app/app.ts
  runtime/src/app/types.ts
  runtime/src/server/middleware/get_page_handler.ts
  site/content/docs/02-routing.md
  site/content/docs/07-state-management.md
  test/apps/errors/src/routes/_layout.svelte
  test/apps/errors/test.ts
Labels: enhancement, error handling

#1548 Update preload example
  site/content/docs/04-preloading.md
Labels: docs

#1560 Collect chunks in generateBundle to fix service worker manifest
  src/core/create_compilers/RollupCompiler.ts
Labels: bug, bundling, service worker

#1557 Mention TypeScript in the docs under "Getting started"
  site/content/docs/00-introduction.md
  site/content/faq/200-webpack-vs-rollup.md
  site/content/faq/300-typescript.md
Labels: docs
