Repository sveltejs/sapper, pull requests merged in 2020-08, with the labels that each got.

#1262 chore: bump sirv version
  package-lock.json
  package.json
  test/apps/export-webpack/webpack.config.js
Labels: dependencies

#1353 Fix docs rendering after recent changes
  site/content/docs/09-building.md
  site/content/migrating/01-migrating.md
  site/src/template.html
Labels: docs

#1173 remove cache-control header
  runtime/src/server/middleware/get_page_handler.ts
  test/apps/basics/test.ts
Labels: breaking

#1067 Remove head hydration workaround
  package.json
  runtime/src/app/app.ts
  runtime/src/server/middleware/get_page_handler.ts
Labels: breaking

#1268 Upgrade Rollup
  package-lock.json
  package.json
  rollup.config.js
  test/apps/basics/rollup.config.js
  test/apps/credentials/rollup.config.js
  test/apps/css/rollup.config.js
  test/apps/custom-extension/rollup.config.js
  test/apps/encoding/rollup.config.js
  test/apps/errors/rollup.config.js
  test/apps/export-multiple-entry/rollup.config.js
  test/apps/export-queue/rollup.config.js
  test/apps/export/rollup.config.js
  test/apps/ignore/rollup.config.js
  test/apps/layout/rollup.config.js
  test/apps/preloading/rollup.config.js
  test/apps/redirects/rollup.config.js
  test/apps/scroll/rollup.config.js
  test/apps/session/rollup.config.js
  test/apps/with-basepath/rollup.config.js
  test/apps/with-sourcemaps/rollup.config.js
Labels: dependencies

#1244 Prefix file paths in SW manifest with a slash
  src/core/create_app.ts
  test/apps/with-sourcemaps-webpack/test.ts
  test/apps/with-sourcemaps/test.ts
Labels: breaking

#1269 Preload CSS and JS dependencies
  package-lock.json
  package.json
  runtime/src/server/middleware/get_page_handler.ts
  src/core/create_compilers/RollupResult.ts
  src/core/create_compilers/interfaces.ts
Labels: enhancement

#1304 better error: show a warning/error when server-preloaded data can't be transmitted to the client
  runtime/src/server/middleware/get_page_handler.ts
Labels: better error

#1320 Add noscroll option to goto, document sapper-noscroll on links
  runtime/src/app/goto/index.ts
  runtime/src/app/start/index.ts
  site/content/docs/03-client-api.md
  site/content/docs/08-link-options.md
  test/apps/scroll/src/routes/search-form.svelte
  test/apps/scroll/test.ts
Labels: docs, enhancement

#1369 Consolidate migration info
  CHANGELOG.md
  site/content/migrating/01-migrating.md
Labels: docs

#1385 Upgrade site dependencies
  site/package-lock.json
  site/package.json
  site/rollup.config.js
Labels: site

#1383 Add webpack vs rollup faq
  site/content/faq/200-webpack-vs-rollup.md
Labels: docs

#1410 Add more questions to FAQ
  site/content/faq/100-version-numbers.md
  site/content/faq/300-typescript.md
  site/content/faq/400-why-is-there-a-node_modules-folder-in-src.md
Labels: docs

#1439 Make dev mode reflect changes to css
  src/core/create_compilers/RollupCompiler.ts
  src/core/create_compilers/RollupResult.ts
  src/core/create_compilers/interfaces.ts
Labels: bug

#1403 docs: mention that exporting now follows images
  site/content/docs/10-exporting.md
Labels: docs

#1372 Don’t prevent the browser’s default behavior corresponding to the Alt key
  runtime/src/app/start/index.ts
Labels: routing

#1452 Fix multiple asset handling issues
  package-lock.json
  package.json
  runtime/src/server/middleware/get_page_handler.ts
  src/api/build.ts
  src/api/dev.ts
  src/core/create_compilers/RollupCompiler.ts
  src/core/create_compilers/RollupResult.ts
  src/core/create_compilers/WebpackResult.ts
  src/core/create_compilers/chunk.ts
  src/core/create_compilers/index.ts
  src/core/create_compilers/inject.ts
  src/core/create_compilers/interfaces.ts
Labels: bundling
