Repository sveltejs/sapper, pull requests merged in 2020-12, with the labels that each got.

#1670 Fix broken url in docs
  site/content/migrating/01-migrating.md
Labels: docs

#1620 Fix runtime router handling of encoded query parameters
  runtime/src/app/router/index.ts
  test/apps/encoding/src/routes/index.html
  test/apps/encoding/test.ts
  tsconfig.json
Labels: routing

#1594 Fixed #1592 by ensuring `scroll` exists
  runtime/src/app/router/index.ts
Labels: routing

#1677 Remove injectImports flag from roll-plugin-css-chunks
  src/core/create_compilers/RollupCompiler.ts
Labels: bug, bundling

#1666 Upgrade rollup-plugin-css-chunks
  package-lock.json
  package.json
  site/content/migrating/01-migrating.md
Labels: breaking, bug, bundling, dependencies

#878 Remove introductory sentance
  site/content/docs/01-structure.md
Labels: docs

#1680 Remove cypress from site project and upgrade dependencies
  site/appveyor.yml
  site/cypress.json
  site/cypress/.eslintrc.js
  site/cypress/fixtures/example.json
  site/cypress/integration/spec.js
  site/cypress/plugins/index.js
  site/cypress/support/commands.js
  site/cypress/support/index.js
  site/package-lock.json
  site/package.json
  site/rollup.config.js
Labels: site

#1682 Fix minor typo in docs
  site/content/docs/04-preloading.md
Labels: docs
