Repository sveltejs/sapper, pull requests merged in 2020-07, with the labels that each got.

#1338 Fix Sapper on Windows
  mocha.opts
  src/core/create_compilers/RollupResult.ts
  src/core/create_compilers/extract_css.ts
  src/utils.ts
  test/unit/utils.test.ts
Labels: bug

#1349 Update old link to migration guide
  CHANGELOG.md
Labels: docs

#1326 Rollup: Explicitly set `output.exports`
  src/core/create_compilers/RollupCompiler.ts
Labels: breaking

#1123 move %sapper.scripts% to <head> with defer
  runtime/src/server/middleware/get_page_handler.ts
  site/src/template.html
  test/apps/basics/src/template.html
  test/apps/credentials/src/template.html
  test/apps/css/src/template.html
  test/apps/custom-extension/src/template.html
  test/apps/encoding/src/template.html
  test/apps/errors/src/template.html
  test/apps/export-multiple-entry/src/template.html
  test/apps/export-queue/src/template.html
  test/apps/export-webpack/src/template.html
  test/apps/export/src/template.html
  test/apps/ignore/src/template.html
  test/apps/layout/src/template.html
  test/apps/preloading/src/template.html
  test/apps/redirects/src/template.html
  test/apps/scroll/src/template.html
  test/apps/session/src/template.html
  test/apps/with-basepath/src/template.html
  test/apps/with-sourcemaps-webpack/src/template.html
  test/apps/with-sourcemaps/src/template.html
Labels: breaking

#1209 Add docs for --legacy flag
  site/content/docs/09-building.md
Labels: docs

#1085 Document the actual use of `export --entry`
  site/content/docs/10-exporting.md
Labels: docs
